<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use App\Models\User;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
     
       \DB::table('tbl_user')->delete();
        \DB::table('tbl_user')->insert(
           [
                "id"=>1,
                "name"=>"Admin",
                "email"=>"vishal.du123@gmail.com",
                "phone"=>"9827530980",
                "image"=>"",
                "password"=>Hash::make("123456"), //chk this
           ]
        );
        \DB::table('tbl_role')->delete();
        \DB::table('tbl_role')->insert(
            [
                    "id"=>1,
                    "name"=>"Super Admin"
            ]);
        \DB::table('tbl_role')->insert(
            [
                    "id"=>2,
                    "name"=>"Admin"
            ]);
        \DB::table('tbl_role')->insert(
            [
                    "id"=>3,
                    "name"=>"Editor"
            ]
        );
        \DB::table('tbl_role_user')->delete();
        \DB::table('tbl_role_user')->insert(
            [
                "id"=>1,
                "userid"=>"1",
                "roleid"=>"1"
            ]);
        \DB::table('tbl_role_user')->insert(
            [
                "id"=>2,
                "userid"=>"1",
                "roleid"=>"2"
            ]);
            \DB::table('tbl_role_user')->insert(
                [
                    "id"=>3,
                    "userid"=>"1",
                    "roleid"=>"3"
                ]
            );
            \DB::table('tbl_menu_access')->delete();
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"1",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin",
                    "name"=>"",
                    "action"=>"App\Http\Controllers\UserAuth@home",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"2",
                    "method"=>"POST",
                    "uri"=>"admin/auth",
                    "name"=>"auth.store",
                    "action"=>"App\Http\Controllers\UserAuth@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"3",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/auth",
                    "name"=>"auth.index",
                    "action"=>"App\Http\Controllers\UserAuth@index",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"4",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/auth/create",
                    "name"=>"auth.create",
                    "action"=>"App\Http\Controllers\UserAuth@create",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"5",
                    "method"=>"DELETE",
                    "uri"=>"admin/auth/{auth}",
                    "name"=>"auth.destroy",
                    "action"=>"App\Http\Controllers\UserAuth@destroy",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"6",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/auth/{auth}",
                    "name"=>"auth.show",
                    "action"=>"App\Http\Controllers\UserAuth@show",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
\DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"7",
                    "method"=>"PUT|PATCH",
                    "uri"=>"admin/auth/{auth}",
                    "name"=>"auth.update",
                    "action"=>"App\Http\Controllers\UserAuth@update",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"8",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/auth/{auth}/edit",
                    "name"=>"auth.edit",
                    "action"=>"App\Http\Controllers\UserAuth@edit",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"9",
                    "method"=>"POST",
                    "uri"=>"admin/category",
                    "name"=>"category.store",
                    "action"=>"App\Http\Controllers\CategoryController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"10",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/category",
                    "name"=>"category.index",
                    "action"=>"App\Http\Controllers\CategoryController@index",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"11",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/category/create",
                    "name"=>"category.create",
                    "action"=>"App\Http\Controllers\CategoryController@create",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"12",
                    "method"=>"POST",
                    "uri"=>"admin/category/save",
                    "name"=>"category.store",
                    "action"=>"App\Http\Controllers\CategoryController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"13",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/category/{category}",
                    "name"=>"category.show",
                    "action"=>"App\Http\Controllers\CategoryController@show",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"14",
                    "method"=>"DELETE",
                    "uri"=>"admin/category/{category}",
                    "name"=>"category.destroy",
                    "action"=>"App\Http\Controllers\CategoryController@destroy",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"15",
                    "method"=>"PUT|PATCH",
                    "uri"=>"admin/category/{category}",
                    "name"=>"category.update",
                    "action"=>"App\Http\Controllers\CategoryController@update",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"16",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/category/{category}/edit",
                    "name"=>"category.edit",
                    "action"=>"App\Http\Controllers\CategoryController@edit",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"17",
                    "method"=>"POST",
                    "uri"=>"admin/check",
                    "name"=>"",
                    "action"=>"App\Http\Controllers\UserAuth@check",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"18",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/login",
                    "name"=>"",
                    "action"=>"App\Http\Controllers\UserAuth@login",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"19",
                    "method"=>"POST",
                    "uri"=>"admin/pages",
                    "name"=>"pages.store",
                    "action"=>"App\Http\Controllers\PagesController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"20",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/pages",
                    "name"=>"pages.index",
                    "action"=>"App\Http\Controllers\PagesController@index",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"21",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/pages/create",
                    "name"=>"pages.create",
                    "action"=>"App\Http\Controllers\PagesController@create",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"22",
                    "method"=>"POST",
                    "uri"=>"admin/pages/save",
                    "name"=>"pages.store",
                    "action"=>"App\Http\Controllers\PagesController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"23",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/pages/{page}",
                    "name"=>"pages.show",
                    "action"=>"App\Http\Controllers\PagesController@show",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"24",
                    "method"=>"PUT|PATCH",
                    "uri"=>"admin/pages/{page}",
                    "name"=>"pages.update",
                    "action"=>"App\Http\Controllers\PagesController@update",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"25",
                    "method"=>"DELETE",
                    "uri"=>"admin/pages/{page}",
                    "name"=>"pages.destroy",
                    "action"=>"App\Http\Controllers\PagesController@destroy",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"26",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/pages/{page}/edit",
                    "name"=>"pages.edit",
                    "action"=>"App\Http\Controllers\PagesController@edit",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"27",
                    "method"=>"POST",
                    "uri"=>"admin/post/save",
                    "name"=>"post.store",
                    "action"=>"App\Http\Controllers\PostController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"28",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/posts",
                    "name"=>"posts.index",
                    "action"=>"App\Http\Controllers\PostController@index",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"29",
                    "method"=>"POST",
                    "uri"=>"admin/posts",
                    "name"=>"posts.store",
                    "action"=>"App\Http\Controllers\PostController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"30",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/posts/create",
                    "name"=>"posts.create",
                    "action"=>"App\Http\Controllers\PostController@create",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"31",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/posts/{post}",
                    "name"=>"posts.show",
                    "action"=>"App\Http\Controllers\PostController@show",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"32",
                    "method"=>"PUT|PATCH",
                    "uri"=>"admin/posts/{post}",
                    "name"=>"posts.update",
                    "action"=>"App\Http\Controllers\PostController@update",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"33",
                    "method"=>"DELETE",
                    "uri"=>"admin/posts/{post}",
                    "name"=>"posts.destroy",
                    "action"=>"App\Http\Controllers\PostController@destroy",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"34",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/posts/{post}/edit",
                    "name"=>"posts.edit",
                    "action"=>"App\Http\Controllers\PostController@edit",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"35",
                    "method"=>"POST",
                    "uri"=>"admin/role",
                    "name"=>"role.store",
                    "action"=>"App\Http\Controllers\RoleController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"36",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/role",
                    "name"=>"role.index",
                    "action"=>"App\Http\Controllers\RoleController@index",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"37",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/role/create",
                    "name"=>"role.create",
                    "action"=>"App\Http\Controllers\RoleController@create",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"38",
                    "method"=>"PUT|PATCH",
                    "uri"=>"admin/role/{role}",
                    "name"=>"role.update",
                    "action"=>"App\Http\Controllers\RoleController@update",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"39",
                    "method"=>"DELETE",
                    "uri"=>"admin/role/{role}",
                    "name"=>"role.destroy",
                    "action"=>"App\Http\Controllers\RoleController@destroy",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"40",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/role/{role}",
                    "name"=>"role.show",
                    "action"=>"App\Http\Controllers\RoleController@show",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"41",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/role/{role}/edit",
                    "name"=>"role.edit",
                    "action"=>"App\Http\Controllers\RoleController@edit",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"42",
                    "method"=>"POST",
                    "uri"=>"admin/users",
                    "name"=>"users.store",
                    "action"=>"App\Http\Controllers\UserController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"43",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/users",
                    "name"=>"users.index",
                    "action"=>"App\Http\Controllers\UserController@index",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"44",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/users/create",
                    "name"=>"users.create",
                    "action"=>"App\Http\Controllers\UserController@create",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"45",
                    "method"=>"POST",
                    "uri"=>"admin/users/save",
                    "name"=>"users.store",
                    "action"=>"App\Http\Controllers\UserController@store",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"46",
                    "method"=>"DELETE",
                    "uri"=>"admin/users/{user}",
                    "name"=>"users.destroy",
                    "action"=>"App\Http\Controllers\UserController@destroy",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"47",
                    "method"=>"PUT|PATCH",
                    "uri"=>"admin/users/{user}",
                    "name"=>"users.update",
                    "action"=>"App\Http\Controllers\UserController@update",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"48",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/users/{user}",
                    "name"=>"users.show",
                    "action"=>"App\Http\Controllers\UserController@show",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"49",
                    "method"=>"GET|HEAD",
                    "uri"=>"admin/users/{user}/edit",
                    "name"=>"users.edit",
                    "action"=>"App\Http\Controllers\UserController@edit",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"50",
                    "method"=>"GET|HEAD",
                    "uri"=>"api/user",
                    "name"=>"",
                    "action"=>"Closure",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
            \DB::table('tbl_menu_access')->insert(
                [
                    "id"=>"51",
                    "method"=>"GET|HEAD",
                    "uri"=>"logout",
                    "name"=>"",
                    "action"=>"App\Http\Controllers\UserAuth@logout",
                    "status"=>"1",
                    "delete"=>"1",
                ]
            );
    }
}
